language: java
sudo: true
jdk:
  - openjdk17
before_install:
  - chmod +x mvnw

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: "book-store-demo"
  on:
    branch: main